CREATE TABLE `image_contributions` (
	`id` integer PRIMARY KEY NOT NULL,
	`user_id` integer NOT NULL,
	`vehicle_id` integer NOT NULL,
	`filename` text NOT NULL,
	`original_filename` text NOT NULL,
	`path` text NOT NULL,
	`alt_text` text,
	`caption` text,
	`file_size` integer,
	`mime_type` text,
	`width` integer,
	`height` integer,
	`status` text DEFAULT 'PENDING' NOT NULL,
	`submitted_at` integer NOT NULL,
	`reviewed_by` integer,
	`reviewed_at` integer,
	`rejection_reason` text,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `vehicle_images` (
	`id` integer PRIMARY KEY NOT NULL,
	`vehicle_id` integer NOT NULL,
	`filename` text NOT NULL,
	`path` text NOT NULL,
	`url` text NOT NULL,
	`alt_text` text,
	`caption` text,
	`display_order` integer DEFAULT 0 NOT NULL,
	`file_size` integer,
	`mime_type` text,
	`width` integer,
	`height` integer,
	`uploaded_by` integer,
	`uploaded_at` integer NOT NULL,
	`is_approved` integer DEFAULT false NOT NULL,
	`approved_by` integer,
	`approved_at` integer,
	FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`approved_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
